### ISSUE TITLE
Type Miss Match from Literal Contract

### ISSUE THREAD

**Issue by jormal** [kupl/MicSE#21]
# Bug Report

## Symptom

- `PUSH @dest (contract :UnitContract unit) "tz1LBEKXaxQbd5Gtzbc1ATCwc3pppu81aWGc"`  makes wrong type `T_contract` not `T_option(T_contract)`

## Scenario and Screenshot

- Running command is
``` bash
$ dune exec -- micse -input ./benchmarks/mutez_active/bd08fc2b11cb47405e22cc8bce9abc7c9a280b5c181733e38297dbddf3546e00.tz
Prover__Verifier.Error("(v213=CONTRACT(ADDRESS(K_tz1LBEKXaxQbd5Gtzbc1ATCwc3pppu81aWGc))) occurs encoding error \"Sorts Contract and Option(Contract) are incompatible\"")
```
- Bug of code is here [c456eb](https://github.com/kupl/MicSE/commit/c456eb580aed1227c7f3ba12fc30e4c78114d3f8)
  This bug fix is wrong. The result of `Push` instruction for `T_contract` should be converted to `V_lit_contract`

## Plan

- Fix it.

## Reference

- [c456eb](https://github.com/kupl/MicSE/commit/c456eb580aed1227c7f3ba12fc30e4c78114d3f8)
- Issue #17

**Comment by jormal** [comment]
@cushionbadak Check plz.

**Comment by cushionbadak** [comment]
According to the nomadic lab's details for [contract type](https://tezos.gitlab.io/michelson-reference/#type-contract), Only implicit accounts (starts with "tz") can be expressed as contract-type literal. `4c812af` commit looks good for this reason.
I'll close this issue.
